# -*- mode: ruby -*-
# vi: set ft=ruby :

# A vagrant config for testing against gcc-4.4.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-10.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/us.archive/old-releases/' /etc/apt/sources.list
    apt-get update
    apt-get install -y g++ make wget
    wget -q https://www.dropbox.com/s/ssvomsla6bkx2wl/cmake-3.14.4-Linux-x86_64.tar.gz
    tar xzf cmake-3.14.4-Linux-x86_64.tar.gz
    ln -s `pwd`/cmake-3.14.4-Linux-x86_64/bin/cmake /usr/local/bin
  SHELL
end
