name: Push Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      #with:
      #  arch: amd64
      #  toolset: 16.0

    - name: CMake
      working-directory: .
      run: cmake .

    - name: Build Release
      working-directory: .
      run: msbuild /m /p:Configuration=Release FMT.sln
      
    - name: Build Debug
      working-directory: .
      run: msbuild /m /p:Configuration=Debug FMT.sln

    - name: Nuget Pack
      working-directory: .
      run: nuget pack fmtlib.nuspec -version 6.1.2 -OutputFileNamesWithoutVersion -OutputDirectory dist
      
    - name: Nuget Push
      working-directory: .
      run: nuget push dist\fmtlib.nupkg